### ISSUE TITLE
Distribution packaging dependencies

### ISSUE THREAD

**Issue by philipzae** [Xfce-Classic/libxfce4ui-nocsd#1]
Congrats on starting up this new initiative. Was curious how you are planning to tackle package management dependencies for the upstream library when other packages are dependent on it.

**Comment by shawnanastasio** [comment]
Are you referring to management of libxfce4ui-nocsd's dependencies, or management of packages that depend on `libxfce4ui-nocsd`?

For the former, all of the library's dependencies are standard system libraries (gtk, etc.), so when those encounter breaking API updates I'll update libxfce4ui-nocsd to be compatible (when possible, of course).

For the latter, the current plan is to adopt a versioning scheme that mirrors upstream libxfce4ui with full API/ABI compatibility, i.e. applications built against libxfce4ui 4.15.3 will be able to run with no modifications against libxfce4ui-nocsd 4.15.3. Currently we're mostly done implementing upstream's 4.15.3 ABI, with a few exceptions. Eventually I'll try to set up some testing infrastructure to ensure that ABI guarantees are met (thankfully, upstream's abicheck.sh provides a good base already).

Let me know if this answered your questions.

**Comment by philipzae** [comment]
management of packages that depend on libxfce4ui, as i presume libxfce4ui-nocsd would be a replacement package for it, or do I have that wrong and simply installing libxfce4ui-nocsd will simply overwrite the libxfce4ui files.

**Comment by shawnanastasio** [comment]
Ah, I see what you mean. You are correct that libxfce4ui-nocsd would be a replacement package that would have to be installed instead of libxfce4ui (or at least, placed higher in the dynamic linker's path list).

**Comment by philipzae** [comment]
![image](https://user-images.githubusercontent.com/4412114/87193030-dc377c80-c308-11ea-86c8-bcadd00798ac.png)

If it is a replacement package, then other packages would need to have something like
**Depends: libxfce4ui | libxfce4ui-nocsd**

**Comment by shawnanastasio** [comment]
> If it is a replacement package, then other packages would need to have something like
> **Depends: libxfce4ui | libxfce4ui-nocsd**

I suppose that's true. Admittedly I'm not super familiar with Debian/Ubuntu's packaging system, but would it be possible to specify the dependency as some sort of virtual package that can be satisfied by either version, rather than listing each possible version in all dependents? Perhaps through the alternatives framework?

It may also be worth checking out unit139's package on the [Xubuntu QA Experimental PPA](https://launchpad.net/~xubuntu-dev/+archive/ubuntu/experimental/+packages) to see how they handled it.

**Comment by philipzae** [comment]
Yes unit139 mentioned in the xubuntu-dev IRC that he was putting it in the Xubuntu PPA, so this issue was just my lack of debian packaging knowledge and wondering how you'd handle debian packaging. I'm jphilips on IRC if you want to get in touch with me about anything.

The word is getting out about your new project, so keep up the great work, as I know people will benefit from it. :D
https://linuxreviews.org/Xfce_Classic_Brings_An_Alternative_To_Those_Who_Do_Not_Want_Xfce_To_Become_GNOME_Light
