### ISSUE TITLE
Unable to make it work with all gtk3 apps

### ISSUE THREAD

**Issue by tio-trom** [Xfce-Classic/libxfce4ui-nocsd#12]
It works well with xfce ones but even if I do  `xfconf-query -c xsettings -p /Gtk/DialogsUseHeader -s false` it would not work with any other CSD gtk3 app. What am I doing wrong? Thanks!

**Comment by ByJumperX4** [comment]
This is only for the Xfce apps that uses CSDs

**Comment by benyaminl** [comment]
@tio-trom Have you read the docs? It only works for.... *fill the blank
