### ISSUE TITLE
libxfce4ui 4.18.0 released

### ISSUE THREAD

**Issue by hphilm** [Xfce-Classic/libxfce4ui-nocsd#15]
Since [XFCE 4.18](https://xfce.org/about/news/?post=1671062400) got released, I wonder if that project is still active ...

**Comment by malnvenshorn** [comment]
With Xfce 4.18 CSDs are optional and disabled by default.

https://alexxcons.github.io/blogpost_8.html

**Comment by hphilm** [comment]
OK, which makes the package **libxfce4ui-nocsd** obsolete ...
