### ISSUE TITLE
Xfce 4.12

### ISSUE THREAD

**Issue by smnthermes** [Xfce-Classic/libxfce4ui-nocsd#2]
It would be nice to fork at Xfce 4.12, since it was the last version with GTK2 support.

**Comment by shawnanastasio** [comment]
The goal of the project is to closely match upstream while reverting invasive user-facing UI/UX changes. A 4.12 fork is out of scope for the project, but if there are particular user-facing UI changes that you would like to see, feel free to submit issues for those.
