### ISSUE TITLE
About dialogs still have CSD

### ISSUE THREAD

**Issue by fulalas** [Xfce-Classic/libxfce4ui-nocsd#3]
I built the whole Xfce family using your fork, and although all Xfce main windows look nice now, it seems about dialogs are still using CSD. Here's an example (they're everywhere):

![Screenshot_2020-12-25_18-10-34](https://user-images.githubusercontent.com/27843666/103120610-5dc76f00-46dd-11eb-987d-a03a98c466c5.png)

Am I missing something?

BTW, thanks for your effort to keep Xfce usable :)

**Comment by shawnanastasio** [comment]
Hi, could you tell me if the behavior persists if you set the `DialogsUseHeader` option to false under `Settings Editor>xsettings>Gtk`?

**Comment by fulalas** [comment]
That's it! Thanks! :)
