### ISSUE TITLE
libxfce4ui-4.17.0 released

### ISSUE THREAD

**Issue by rijenkii** [Xfce-Classic/libxfce4ui-nocsd#9]
https://gitlab.xfce.org/xfce/libxfce4ui/-/tags/libxfce4ui-4.17.0

**Comment by shawnanastasio** [comment]
Sorry for the delay - upstream changes for 4.17.0 have now been merged in and a release has been tagged.

**Comment by rijenkii** [comment]
Sorry to bother, but it seems like you didn't move the HEAD of the master branch -- it still points to da0684f, and github says that 857525a "does not belong to any branch on this repository". I think simple `git reset 857525a` should be enough.

**Comment by shawnanastasio** [comment]
You are correct - I had pushed the tag but forgot to push the master branch. Should be fixed now.
